os: linux
dist: trusty
sudo: false
language: java
jdk: oraclejdk8

branches:
  only:
  - master

before_cache:
- rm -rf $HOME/.cache/bazel/_bazel_travis/install/
cache:
  directories:
  - $HOME/local
  - $HOME/.bazel
  - $HOME/.cache/bazel

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - build-essential
    - g++

before_install:
- .travis/install-bazel.sh 0.3.1
- pip install --user virtualenv
# kill pip, wheel and setuptools because rules_pypi manages them and
# we want to test it.
- virtualenv --no-setuptools --no-wheel --no-pip $HOME/dummyenv
- . $HOME/dummyenv/bin/activate
- python --version
- bazel version
- bazel info
- bazel fetch --curses=no -- "//..."
install:
- bazel build $BAZEL_BUILD_OPTS --show_progress_rate_limit 0 -- //...
script:
- bazel test $BAZEL_BUILD_OPTS --show_progress_rate_limit 0 --test_output=streamed -- //...

env:
  global:
  - PATH=$PATH:$HOME/local/bin
  - BAZEL_BUILD_OPTS="--curses=no --genrule_strategy=standalone --spawn_strategy=standalone --verbose_failures -j 20"
